const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    price: 799,
    discount: 10,
    qty: 120,
    artifact: "electronics",
    rating: 4.3,
    images: ["mouse1.jpg", "mouse2.jpg"],
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    price: 2499,
    discount: 15,
    qty: 60,
    artifact: "electronics",
    rating: 4.6,
    images: ["keyboard1.jpg"],
  },
  {
    id: 3,
    name: "USB-C Charger",
    price: 999,
    discount: 20,
    qty: 200,
    artifact: "accessories",
    rating: 4.2,
    images: ["charger1.jpg"],
  },
  {
    id: 4,
    name: "Bluetooth Headphones",
    price: 3499,
    discount: 18,
    qty: 80,
    artifact: "audio",
    rating: 4.5,
    images: ["headphone1.jpg"],
  },
  {
    id: 5,
    name: "Laptop Stand",
    price: 1299,
    discount: 12,
    qty: 150,
    artifact: "office",
    rating: 4.4,
    images: ["stand1.jpg"],
  },
  {
    id: 6,
    name: "Smart Watch",
    price: 5999,
    discount: 25,
    qty: 45,
    artifact: "wearable",
    rating: 4.1,
    images: ["watch1.jpg"],
  },
  {
    id: 7,
    name: "Fitness Band",
    price: 1999,
    discount: 30,
    qty: 100,
    artifact: "wearable",
    rating: 4.0,
    images: ["band1.jpg"],
  },
  {
    id: 8,
    name: "External Hard Drive 1TB",
    price: 4799,
    discount: 14,
    qty: 70,
    artifact: "storage",
    rating: 4.6,
    images: ["hdd1.jpg"],
  },
  {
    id: 9,
    name: "USB Flash Drive 64GB",
    price: 699,
    discount: 22,
    qty: 300,
    artifact: "storage",
    rating: 4.3,
    images: ["usb1.jpg"],
  },
  {
    id: 10,
    name: "Gaming Mouse Pad",
    price: 499,
    discount: 10,
    qty: 180,
    artifact: "gaming",
    rating: 4.2,
    images: ["mousepad1.jpg"],
  },
  {
    id: 11,
    name: "Webcam HD",
    price: 2299,
    discount: 16,
    qty: 55,
    artifact: "electronics",
    rating: 4.1,
    images: ["webcam1.jpg"],
  },
  {
    id: 12,
    name: "Portable Speaker",
    price: 2799,
    discount: 19,
    qty: 90,
    artifact: "audio",
    rating: 4.4,
    images: ["speaker1.jpg"],
  },
  {
    id: 13,
    name: "Power Bank 20000mAh",
    price: 1899,
    discount: 21,
    qty: 140,
    artifact: "accessories",
    rating: 4.5,
    images: ["powerbank1.jpg"],
  },
  {
    id: 14,
    name: "HDMI Cable",
    price: 399,
    discount: 8,
    qty: 250,
    artifact: "accessories",
    rating: 4.0,
    images: ["hdmi1.jpg"],
  },
  {
    id: 15,
    name: "Wireless Earbuds",
    price: 2999,
    discount: 20,
    qty: 85,
    artifact: "audio",
    rating: 4.3,
    images: ["earbuds1.jpg"],
  },
  {
    id: 16,
    name: "Tablet Cover",
    price: 899,
    discount: 13,
    qty: 160,
    artifact: "accessories",
    rating: 4.1,
    images: ["cover1.jpg"],
  },
  {
    id: 17,
    name: "Desk Lamp LED",
    price: 1599,
    discount: 17,
    qty: 110,
    artifact: "office",
    rating: 4.4,
    images: ["lamp1.jpg"],
  },
  {
    id: 18,
    name: "Noise Cancelling Headset",
    price: 6999,
    discount: 22,
    qty: 40,
    artifact: "audio",
    rating: 4.6,
    images: ["headset1.jpg"],
  },
  {
    id: 19,
    name: "Router Dual Band",
    price: 3299,
    discount: 15,
    qty: 65,
    artifact: "networking",
    rating: 4.2,
    images: ["router1.jpg"],
  },
  {
    id: 20,
    name: "Monitor 24 inch",
    price: 12499,
    discount: 18,
    qty: 30,
    artifact: "electronics",
    rating: 4.5,
    images: ["monitor1.jpg"],
  },
  {
    id: 21,
    name: "Keyboard & Mouse Combo",
    price: 1499,
    discount: 20,
    qty: 95,
    artifact: "electronics",
    rating: 4.3,
    images: ["combo1.jpg"],
  },
  {
    id: 22,
    name: "Graphics Tablet",
    price: 4499,
    discount: 12,
    qty: 50,
    artifact: "design",
    rating: 4.4,
    images: ["tablet1.jpg"],
  },
  {
    id: 23,
    name: "Laptop Backpack",
    price: 2199,
    discount: 18,
    qty: 130,
    artifact: "bags",
    rating: 4.5,
    images: ["bag1.jpg"],
  },
  {
    id: 24,
    name: "Cooling Pad",
    price: 1099,
    discount: 14,
    qty: 140,
    artifact: "laptop",
    rating: 4.2,
    images: ["coolpad1.jpg"],
  },
  {
    id: 25,
    name: "Smart Plug",
    price: 999,
    discount: 20,
    qty: 170,
    artifact: "smart-home",
    rating: 4.1,
    images: ["plug1.jpg"],
  },
  {
    id: 26,
    name: "VR Headset",
    price: 8999,
    discount: 25,
    qty: 25,
    artifact: "gaming",
    rating: 4.3,
    images: ["vr1.jpg"],
  },
  {
    id: 27,
    name: "Wireless Presenter",
    price: 1299,
    discount: 11,
    qty: 75,
    artifact: "office",
    rating: 4.0,
    images: ["presenter1.jpg"],
  },
  {
    id: 28,
    name: "Microphone USB",
    price: 3499,
    discount: 19,
    qty: 60,
    artifact: "audio",
    rating: 4.5,
    images: ["mic1.jpg"],
  },
  {
    id: 29,
    name: "Smart Bulb",
    price: 799,
    discount: 16,
    qty: 190,
    artifact: "smart-home",
    rating: 4.2,
    images: ["bulb1.jpg"],
  },
  {
    id: 30,
    name: "Laptop Sleeve",
    price: 699,
    discount: 10,
    qty: 210,
    artifact: "bags",
    rating: 4.1,
    images: ["sleeve1.jpg"],
  },
];

export default products;
